services:
  broker1:
    image: docker.io/bitnami/kafka:3.9
    container_name: broker1
    network_mode: "host"
    hostname: localhost
    user: "1000"
    environment:
      # KRaft settings
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@${NODE1_INTERNAL_IP}:9093,2@${NODE2_INTERNAL_IP}:9093,3@${NODE3_INTERNAL_IP}:9093
      - KAFKA_KRAFT_CLUSTER_ID=testclusterid

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${NODE1_INTERNAL_IP}:9092,EXTERNAL://${NODE1_EXTERNAL_IP}:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    volumes:
      - /data/kafka:/bitnami/kafka
      
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    network_mode: "host"
    hostname: localhost
    depends_on:
      - broker1
    environment:
      KAFKA_CLUSTERS_0_NAME: testcluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${NODE1_INTERNAL_IP}:9092,${NODE2_INTERNAL_IP}:9092,${NODE3_INTERNAL_IP}:9092
      SERVER_PORT: 9000